### ISSUE TITLE
As a developer, I need to document our definition of ready as an Issue template

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-simulation-runner#12]
As a team, we need to document our definition of done as a markdown template to pre-populate our Pull Requests

### Resources
- [How to create an Issue Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)
- [Examples](https://github.com/stevemao/github-issue-templates/tree/master)

### Acceptance Criteria
- [x] The Definition of Ready is documented into an Issue template that can be used.

**Comment by ReeboksTeen23** [comment]
Definition of Ready:
-A set of agreements that determine when something is ready to begin, e.g., when a user story is ready to be taken into a sprint or when all necessary conditions are right for a team to start a sprint. 

1. Need to be properly informed on how to do a story before starting it
2. Make sure that the stories are taken on when you expect that you can complete them
3. Make sure that there are proper materials to complete stories before starting them
4. Need to discuss stories as a group before adding them to the backlog
5. Having a contingency plan for when shit hits the fan
6. Have a game plan on how to complete the story
7. To start a story the team needs to agree that a story has enough detail on what should be done and that it is close enough to the project manager's idea

**Comment by chris-marfia** [comment]
@Access-Point-Program/hocus-pocus Is this task completed if there is still an open pull request for it?
