### ISSUE TITLE
SPIKE: As a team, we need to learn how to create a Spring Boot application

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-simulation-runner#13]
As a team, you will meet with your instructor and learn the basics of Spring Boot applications and terminology. Throughout the Sprint you will need to complete the Getting Start with Spring Guide.

### Resources
- [Getting Started with Spring Tutorial](https://spring.io/guides/tutorials/rest/)

### Acceptance Criteria 
- [x] Every member of the team completes the Spring Tutorial.
- [x] Every member of the team submits their code as a pull request to the provided GitHub Repository for Spring tutorials
  - This will be provided during the first lecture on Spring Boot

**Comment by GabrielIvey0** [comment]
Currently working on this

**Comment by GabrielIvey0** [comment]
https://stackoverflow.com/questions/15598210/the-import-javax-persistence-cannot-be-resolved/74996933#74996933 - Java persistence is outdated in the tutorial
