### ISSUE TITLE
As a developer, I need to create the sidebar of our application

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-simulation-runner#33]
### Description

We need to create the sidebar of our application. It does not need to be fully functional at the moment. However, it should match the design provided to us by our instructor

### Acceptance Criteria

> Add more if needed

- [ ] When we load our UI the sidebar is loaded on the left-hand side of our UI application. 

### Definition of Ready

- [ ] Need to be properly informed on how to do a story before starting it
- [ ] Make sure that the stories are taken on when you expect that you can complete them
- [ ] Make sure that there are proper materials to complete stories before starting them
- [ ] Need to discuss stories as a group before adding them to the backlog
- [ ] Having a contingency plan
- [ ] Have a game plan on how to complete the story
- [ ] To start a story the team needs to agree that a story has enough detail on what should be done and that it is close enough to the project manager's idea

**Comment by calisward** [comment]
Sidebar is fixed and pushed
