### ISSUE TITLE
As a developer, I need to create the settings for our UI application

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-simulation-runner#34]
### Description

At the moment we need to create the settings that are in our UI application. We currently don't have data for this so we will need to mock the data that is being used.

### Acceptance Criteria

> Add more if needed

- [ ] We should have a UI for editing settings available in our UI that matches the mockup provided by our instructor. 

### Definition of Ready

- [ ] Need to be properly informed on how to do a story before starting it
- [ ] Make sure that the stories are taken on when you expect that you can complete them
- [ ] Make sure that there are proper materials to complete stories before starting them
- [ ] Need to discuss stories as a group before adding them to the backlog
- [ ] Having a contingency plan
- [ ] Have a game plan on how to complete the story
- [ ] To start a story the team needs to agree that a story has enough detail on what should be done and that it is close enough to the project manager's idea

**Comment by calisward** [comment]
I added the settings ui to the database repo, whoops.
